### ISSUE TITLE
improve regex documentation

### ISSUE THREAD

**Issue by lepapareil** [Orange-OpenSource/hurl-dev#16]
`hurl version: 1.2.0`

A regex section on the documentation should describe which regex engine is used by hurl (pcre ? perlre ? etc ...) giving some links to official documentation. May be on this empty https://hurl.dev/docs/asserting-response.html#regex-assert section ?

**Comment by fabricereix** [comment]
It could be useful,but that might be too low-level for the documentation. That may be something you look into in the source code and is more related to the implementation.

**Comment by fabricereix** [comment]
In the same category, we use libxml2 for the xpath engine.

**Comment by lepapareil** [comment]
- are there differences in grammar between the all regex engines => yes
- are there differences in grammar between the all xpath, jsonpath engines => yes

I think the documentation should be aimed at all types of users and not only at those who can understand the source code.
The clearer the documentation, the easier it is to use.
