### ISSUE TITLE
Header overlaps linked content

### ISSUE THREAD

**Issue by humphd** [Orange-OpenSource/hurl-dev#50]
This may not be your bug, but it affects your docs.

If I deep link into a section of the docs, for example https://hurl.dev/docs/man-page.html#test, the header at the top sits on top of the `--test` content, making it impossible to share the link:

https://user-images.githubusercontent.com/427398/159532269-96a7cda6-e7d3-4a76-b232-37040999a152.mov

I think the `.doc` class needs a larger `margin-top` in order to compensate.

**Comment by jcamiel** [comment]
Yes, you're right,  it's not good right now. The fixed header is messing with the anchors (it's working on mobile screen where there is no fixed header). I'll try to improve it (I fear the `margin-top` will not be sufficient)

**Comment by jcamiel** [comment]
Could you give it a try @humphd I've updated the css and hopefully links should be better now!

**Comment by humphd** [comment]
Fantastic

<img width="1395" alt="Screen Shot 2022-03-22 at 5 54 43 PM" src="https://user-images.githubusercontent.com/427398/159582796-2e0b5ce8-d2af-4ed4-b11d-85ee1ab9b57a.png">

**Comment by humphd** [comment]
Tested on various breakpoints, everything works.  Nice job.

**Comment by jcamiel** [comment]
Nice! Thanks for the feedbacks, as usual!
