### ISSUE TITLE
[doc] document that hurl is available in nix/nixos

### ISSUE THREAD

**Issue by Jiehong** [Orange-OpenSource/hurl-dev#52]
Hi,

In the installation section of the website (https://hurl.dev/docs/installation.html), you could say that hurl is avaible in NixOS / Nix:

https://search.nixos.org/packages?channel=21.11&from=0&size=50&sort=relevance&type=packages&query=hurl

**Comment by jcamiel** [comment]
Hi @Jiehong (I've transferred this issue to our doc repository).

It's a good suggestion, do you think it's possible to hava a kind of "permalink" to the NixOs Hurl package ?
I would prefer a direct link to Hurl package (kind of Hurl crate https://crates.io/crates/hurl or Hurl Home-brew package https://formulae.brew.sh/formula/hurl#default).
I see also that the NixOs package is not up to date (latest Hurl version is 1.6.1, NixOs package is 1.4.1), I will try to find how to update it (maybe you've some ideas?).

**Comment by Jiehong** [comment]
@jcamiel : Thanks for having moved that ticket.

I tried making a link only to hurl, but nixOS search doesn't allow me to do that.

I tricked the search with limiting 1 element per page (since hurl is the first one): https://search.nixos.org/packages?channel=21.11&show=hurl&from=0&size=1&sort=relevance&type=packages&query=hurl

the NixOS version I showed is for the current stable version of NixOS, but it's already at 1.6.1 in unstable. Unstable will become stable in May or June: https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=hurl

We could link to the source repository that builds hurl for nixos (https://github.com/NixOS/nixpkgs/blob/nixos-21.11/pkgs/tools/networking/hurl/default.nix), but it doesn't tell you how to install it, so it's not that helpful (unless you want to compile it yourself with nix…)

**Comment by jcamiel** [comment]
Ok we can use the refined links !

**Comment by jcamiel** [comment]
Thanks for the feedback @Jiehong the documentation at https://hurl.dev/docs/installation.html should be updated in a few minutes (fell free to make a PR if you want to update the wording)!
